name: GitHub Actions Runner in Docker
on:
  push:
    branches:
      - master
    paths:
      - 'actions-runner-config.sh'
      - 'docker-add-provisioners.json'
      - 'docker-base.json'
      - 'docker-entrypoint.sh'
      - 'docker-ubuntu1*04.json'
      - 'merge-packer-templates.py'
      - 'replace-scripts.json'
      - '.github/workflows/docker-runner.yml'
      - 'etc'
      - 'installers'
      - 'virtual-environments'

jobs:
  base:
    runs-on: [self-hosted]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build bionic and xenial base with packer
        run: packer build docker-base.json
  bionic:
    needs: [base]
    runs-on: [self-hosted]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 720
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up ssh-agent with td-aws-dev and devops_deploy_DEV
        uses: webcoast-dk/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.DEVOPS_DEPLOY_DEV }}
      - name: Set up packer docker directory
        run: |
          rm -frv docker-1804
          mkdir docker-1804
          cp -frv virtual-environments/images/linux/* docker-1804/
          cp -frv installers/* docker-1804/scripts/installers/
          cp -frv etc docker-1804/
          cp -fv actions-runner-install.sh docker-1804/
          cp -fv actions-runner-config.sh docker-1804/
          cp -fv docker-entrypoint.sh docker-1804/
      - name: Merge packer templates
        run: |
          ./merge-packer-templates.py \
            -t docker-1804/ubuntu1804.json \
            -u virtual-environments/images/linux/ubuntu1804.json \
            -g docker-ubuntu1804.json \
            -a docker-add-provisioners.json
      - name: Build 1804 with packer
        run: |
          cd docker-1804
          export PACKER_LOG=1
          packer build \
            -var commit_url="${{ github.ref }}" \
            -var build_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            -var vcs_ref="$(git rev-parse --verify HEAD | cut -c1-8)" \
            -var docker_username="${{ secrets.DOCKER_USERNAME }}" \
            -var docker_password="${{ secrets.DOCKER_PASSWORD }}" \
            -var github_feed_token="${{ secrets.GH_PAT }}" \
            ubuntu1804.json
      - name: Get the updated Docker-Ubuntu1804-README.md file
        run: cp -frv docker-1804/Ubuntu1804-README.md ./Docker-Ubuntu1804-README.md
      - name: Remove the packer working directory
        run: rm -frv docker-1804
      - name: Set up Git
        run: |
          git config --local user.email "sysadmin@terradatum.com"
          git config --local user.name "Terradatum Automation"
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
      - name: Add, commit, pull, and then push changes
        run: |
          echo ${{ github.ref }}
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m "ci: Update Docker-Ubuntu1804-README.md [skip ci]" -a
            git pull --rebase
            git push
          fi
  xenial:
    needs: [base]
    runs-on: [self-hosted]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 720
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up ssh-agent with td-aws-dev and devops_deploy_DEV
        uses: webcoast-dk/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.DEVOPS_DEPLOY_DEV }}
      - name: Set up packer docker directory
        run: |
          rm -frv docker-1604
          mkdir docker-1604
          cp -frv virtual-environments/images/linux/* docker-1604/
          cp -frv installers/* docker-1604/scripts/installers/
          cp -frv etc docker-1604/
          cp -fv actions-runner-install.sh docker-1604/
          cp -fv actions-runner-config.sh docker-1604/
          cp -fv docker-entrypoint.sh docker-1604/
      - name: Merge packer templates
        run: |
          ./merge-packer-templates.py \
            -t docker-1604/ubuntu1604.json \
            -u virtual-environments/images/linux/ubuntu1604.json \
            -g docker-ubuntu1604.json \
            -a docker-add-provisioners.json
      - name: Build 1604 with packer
        run: |
          cd docker-1604
          export PACKER_LOG=1
          packer build \
            -var commit_url="${{ github.ref }}" \
            -var build_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            -var vcs_ref="$(git rev-parse --verify HEAD | cut -c1-8)" \
            -var docker_username="${{ secrets.DOCKER_USERNAME }}" \
            -var docker_password="${{ secrets.DOCKER_PASSWORD }}" \
            -var github_feed_token="${{ secrets.GH_PAT }}" \
            ubuntu1604.json
      - name: Get the updated Docker-Ubuntu1604-README.md file
        run: cp -frv docker-1804/Ubuntu1604-README.md ./Docker-Ubuntu1604-README.md
      - name: Remove the packer working directory
        run: rm -frv docker-1604
      - name: Set up Git
        run: |
          git config --local user.email "sysadmin@terradatum.com"
          git config --local user.name "Terradatum Automation"
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
      - name: Add, commit, pull, and then push changes
        run: |
          echo ${{ github.ref }}
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m "ci: Update Docker-Ubuntu1604-README.md [skip ci]" -a
            git pull --rebase
            git push
          fi
