name: GitHub Actions Runner in Docker - Base Image
on:
  push:
    branches:
      - master
    paths:
      - 'installers/**'
      - 'ubuntu1?04.json'
      - 'virtual-environments'
      - '.github/workflows/main.yml'

# Force the build much?
# See: https://github.community/t5/GitHub-Actions/Action-ignores-included-path/m-p/54170#M9084
jobs:
  bionic:
    runs-on: [self-hosted]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 720
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up packer template_dir
      run: |
        /bin/rm -frv tmp_1804
        /bin/mkdir tmp_1804
        /bin/cp -frv virtual-environments/images/linux/* tmp_1804/
        /bin/cp -frv installers/* tmp_1804/scripts/installers/
        /bin/cp -fv initctl_faker tmp_1804/
    - name: Merge packer templates
      run: jq -s '.[0] as $o1 | .[1] as $o2 | .[2] as $o3 | ($o1 + $o2) |.provisioners = ($o2.provisioners + $o1.provisioners) |del(.provisioners[-1]) |.provisioners[10].scripts += $o3.scripts' virtual-environments/images/linux/ubuntu1804.json ubuntu1804.json add-scripts.json > tmp_1804/ubuntu1804.json
    - name: Build 1804 with packer
      run: |
        cd tmp_1804
        packer build \
          -var commit_url="${{ github.ref }}" \
          -var build_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
          -var vcs_ref="$(git rev-parse --verify HEAD | cut -c1-8)" \
          -var docker_username="${{ secrets.DOCKER_USERNAME }}" \
          -var docker_password="${{ secrets.DOCKER_PASSWORD }}" \
          -var github_feed_token="${{ secrets.GH_PAT }}" \
          ubuntu1804.json
    - name: Get the updated Ubuntu1804-README.md file
      run: cp -frv tmp_1804/Ubuntu1804-README.md ./
    - name: Remove the packer working directory
      run: rm -frv tmp_1804
    - name: Set up Git
      run: |
        git config --local user.email "sysadmin@terradatum.com"
        git config --local user.name "Terradatum Automation"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${GITHUB_REPOSITORY}.git
    - name: Add, commit, pull, and then push changes
      run: |
        echo ${{ github.ref }}
        git add .
        if output=$(git status --porcelain) && [ ! -z "$output" ]; then
          git commit -m "ci: Update Ubuntu1804-README.md [skip ci]" -a
          git pull --rebase
          git push
        fi
    - name: Dispatch "deploy" Bionic
      run: |
        curl -X POST https://api.github.com/repos/terradatum/github-runner/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: token ${{ secrets.GH_PAT }}' \
          --data '{"event_type": "deploy-bionic"}'
      if: "!contains(github.event.head_commit.message, 'downstream skip') && !contains(github.event.head_commit.message, 'skip downstream')"
  xenial:
    runs-on: [self-hosted]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 720
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up packer template_dir
        run: |
          rm -frv tmp_1604
          mkdir tmp_1604
          /bin/cp -frv virtual-environments/images/linux/* tmp_1604/
          /bin/cp -frv installers/* tmp_1604/scripts/installers/
          /bin/cp -fv initctl_faker tmp_1604/
      - name: Merge packer templates
        run: jq -s '.[0] as $o1 | .[1] as $o2 | .[2] as $o3 | ($o1 + $o2) |.provisioners = ($o2.provisioners + $o1.provisioners) |del(.provisioners[-1]) |.provisioners[10].scripts += $o3.scripts' virtual-environments/images/linux/ubuntu1604.json ubuntu1604.json add-scripts.json > tmp_1604/ubuntu1604.json
      - name: Build 1604 with packer
        run: |
          cd tmp_1604
          packer build \
            -var commit_url=${{ github.ref }} \
            -var build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            -var vcs_ref=${GITHUB_SHA::8} \
            -var docker_username=${{ secrets.DOCKER_USERNAME }} \
            -var docker_password=${{ secrets.DOCKER_PASSWORD }} \
            -var github_feed_token=${{ secrets.GH_PAT }} \
            ubuntu1604.json
      - name: Get the updated Ubuntu1604-README.md files
        run: cp -frv tmp_1604/Ubuntu1604-README.md ./
      - name: Remove the packer working directory
        run: rm -frv tmp_1604
      - name: Set up Git
        run: |
          git config --local user.email "sysadmin@terradatum.com"
          git config --local user.name "Terradatum Automation"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${GITHUB_REPOSITORY}.git
      - name: Add, commit, pull, and then push changes
        run: |
          echo ${{ github.ref }}
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m "ci: Update Ubuntu1604-README.md [skip ci]" -a
            git pull --rebase
            git push
          fi
      - name: Dispatch "deploy" Xenial
        run: |
          curl -X POST https://api.github.com/repos/terradatum/github-runner/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -H 'Authorization: token ${{ secrets.GH_PAT }}' \
            --data '{"event_type": "deploy-xenial"}'
        if: "!contains(github.event.head_commit.message, 'downstream skip') && !contains(github.event.head_commit.message, 'skip downstream')"
