name: GitHub Actions Runner in Docker - Release
on:
  push:
    paths-ignore:
      - README.md
    tags:
      - '*'

jobs:
  ubuntu_latest_tag:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: Checkout virtual-environments submodule
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: get version
      run: echo ::set-env name=TAG::${GITHUB_REF#refs/tags/}
    - name: Get GitHub organization or user
      run: echo ::set-env name=ORG::$(dirname ${GITHUB_REPOSITORY})
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Build
      run: docker buildx build --squash -f Dockerfile -t ${ORG}/github-runner:${TAG}-ubuntu-rolling -t ${ORG}/github-runner:${TAG}-ubuntu-eoan -t ${ORG}/github-runner:${TAG}-ubuntu-19.10 --output "type=image,push=true" --platform linux/amd64,linux/arm/v7,linux/arm64 .
  ubuntu_xenial_tag:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: Checkout virtual-environments submodule
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: get version
      run: echo ::set-env name=TAG::${GITHUB_REF#refs/tags/}
    - name: Get GitHub organization or user
      run: echo ::set-env name=ORG::$(dirname ${GITHUB_REPOSITORY})
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Copy Dockerfile
      run: |
       cp Dockerfile Dockerfile.ubuntu-xenial
       sed -i'' 's/FROM.*/FROM ubuntu:xenial/; s/1804/1604/' Dockerfile.ubuntu-xenial
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Build
      run: docker buildx build --squash -f Dockerfile.ubuntu-xenial -t ${ORG}/github-runner:${TAG}-ubuntu-xenial -t ${ORG}/github-runner:${TAG}-ubuntu-16.04 --output "type=image,push=true" --platform linux/amd64,linux/arm/v7,linux/arm64 .
